function process {
        SERVICENAME=" rpi_omx_trigger"
        echo "enabling $SERVICENAME"
        sudo systemctl daemon-reload
        sudo systemctl enable $SERVICENAME.service
        sudo systemctl restart $SERVICENAME.service
        sudo systemctl restart rpi_omx_trigger_sensor.service
        sudo systemctl restart rpi_omx_trigger_sensor.service
}


post_install() {
        process
}

post_upgrade() {
        process
}
           
